version: "3.9"

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes: 
    - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    command: streamlit run main.py --server.port=8080 --server.address=0.0.0.0
    ports: 
      - "8080:8080"
    depends_on:
      - web 

volumes:
  postgres_data:
