# Generated by Django 5.1.7 on 2025-07-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('NOT_DONE', 'Not Done')], default='NOT_DONE', max_length=10),
        ),
    ]
